[package]
name = "leetcode-practice"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
chrono = "0.4.39"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "problems"
harness = false
