version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: pg-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: db
    ports:
      - "5445:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: